-- Q1 NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES
     SELECT ENAME,LOC
     FROM EMP INNER JOIN DEPT
     OM EMP.DEPTNO=DEPT.DEPTNO;

-- Q2 WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEES WORKING IN ACCOUNTING

-- Q3 WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOSE SALARY IS MORE THAN 2340

-- Q4 WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CHARACTER 'A' IN THEIR DNAME

-- Q5 WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN

-- Q6 WAQTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOSE JOB AND DNAME START WITH CHARACTER 'S'

-- Q7 WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839

-- Q8 WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 1983 INTO ACCOUNTING OR RESEARCH DEPT

-- Q9 WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30

-- Q10 WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHOSE EMPNO ARE (7839, 7902) AND ARE WORKING IN LOC NEW YORKA
