-- Q1 WAQTD name of the employee and his location of all the employees.
SELECT ENAME,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;

-- Q2 WAQTD DNAME and SALARY for all the employees working in ACCOUNTING.
SELECT DNAME,SAL,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DNAME='ACCOUNTING';
--Q3 WAQTD DNAME and ANNUAL SALARY for all employees whose salary is more than 2340.
SELECT DNAME,SAL*12
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL>2340;
 --Q4 WAQTD ENAME and DNAME for employees having character 'A' in their DNAME.
 SELECT ENAME,DNAME
 FROM EMP INNER JOIN DEPT
 ON EMP.DEPTNO=DEPT.DEPTNO
 WHERE DNAME LIKE '%A%';

--Q5 WAQTD ENAME and DNAME for all the employees working as SALESMAN.
SELECT ENAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB='SALESMAN';

--Q6 WAQTD DNAME and JOB for all the employees whose JOB and DNAME start with character 'S'.
SELECT DNAME,JOB
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB LIKE '%S%' AND DNAME LIKE '%S%';


--Q7 WAQTD DNAME and MGR NO for employees reporting to 7839.
SELECT DNAME,MGR
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE MGR=(SELECT EMPNO
           FROM EMP 
           WHERE EMPNO=7839);
--Q8 WAQTD DNAME and HIREDATE for employees hired after 83 into ACCOUNTING or RESEARCH department.
SELECT DNAME,HIREDATE
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE HIREDATE > '31-DEC-83' AND
                 EMP.DEPTNO IN(SELECT DEPTNO
                          FROM DEPT
                          WHERE DNAME='ACCOUNTING' OR DNAME='RESEARCH')

--Q9 WAQTD ENAME and DNAME of the employees who are getting commission in DEPT 10 or 30.
SELECT ENAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.COMM IS NOT NULL
AND EMP.DEPTNO IN(SELECT DEPTNO
                 FROM EMP
                 WHERE DEPTNO=10 OR DEPTNO=30);


--Q10 WAQTD DNAME and EMPNO for all the employees whose EMPNO are (7839, 7902) and are working in location NEW YORK.
SELECT DNAME,EMPNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.EMPNO IN(SELECT EMPNO
                   FROM EMP
                   WHERE EMPNO=7839 OR EMPNO=7902
                   AND DEPT.DEPTNO=(SELECT DEPTNO
                                    FROM DEPT
                                    WHERE LOC='NEWYORK'));
