-- Q1 WAQTD 3rd MAXIMUM SALARY OF THE EMPLOYEES
    SELECT SAL
    FROM(SELECT ROWNUM SINO,SAL
    FROM(SELECT DISTINCT SAL
        FROM EMP
        ORDER BY SAL DESC))
    WHERE SINO=3;

-- Q2 WAQTD 1ST MIN AND 5th MINIMUM SALARY OF THE EMPLOYEES
     SELECT SAL
     FROM(SELECT ROWNUM SINO,SAL
          FROM(SELECT DISTINCT SAL
               FROM EMP
               ORDER BY SAL ASC))
               WHERE SINO IN(1,5);

-- Q3 WAQTD 1st MAXIMUM SALARY AND LAST MAX OF SALARY OF THE EMPLOYEES
   SELECT SAL
   FROM(SELECT ROWNUM SINO,SAL
        FROM(SELECT DISTINCT SAL
             FROM EMP
             ORDER BY SAL DESC))
             WHERE SINO =1 OR SINO=(SELECT COUNT(DISTINCT SAL)
                          FROM EMP);

                          OR
    SELECT MAX(SAL),MIN(SAL)
    FROM EMP;
-- Q4 WAQTD FIRST 50% MINIMUM SALARY OF THE EMPLOYEES
      SELECT SAL
       FROM(SELECT ROWNUM SINO,SAL
             FROM(SELECT DISTINCT SAL
                  FROM EMP
                  ORDER BY SAL))
        WHERE SINO<=(SELECT CEIL(COUNT(DISTINCT SAL)*50/100)
                     FROM EMP);
-- Q5 WAQTD FIRST 25% MAXIMUM SALARY OF THE EMPLOYEES
      SELECT SAL
      FROM(SELECT ROWNUM SINO,SAL
          FROM(SELECT DISTINCT SAL
               FROM EMP
               ORDER BY SAL DESC))
     WHERE SINO<= (SELECT CEIL(COUNT(DISTINCT SAL)*25/100)
                    FROM EMP);

-- Q6 WAQTD FIRST 75% OF MAXIMUM SALARY OF THE EMPLOYEES
      SELECT SAL
      FROM(SELECT ROWNUM SINO,SAL
            FROM(SELECT DISTINCT SAL
                 FROM EMP
                 ORDER BY SAL DESC))
      WHERE SINO<=(SELECT CEIL(COUNT(DISTINCT SAL)*75/100)
                    FROM EMP);

-- Q7 WAQTD LAST 3 MINIMUM SALARY OF THE EMPLOYEES
    SELECT SAL
     FROM(SELECT ROWNUM SINO,SAL
          FROM(SELECT DISTINCT SAL
               FROM EMP
               ORDER BY SAL))
     WHERE SINO>(SELECT (COUNT(DISTINCT SAL)-3)
                  FROM EMP)
                  --?
                  WHERE RN > (SELECT COUNT(DISTINCT SAL) - 3 FROM EMP);
-- Q8 WAQTD LAST 50% OF MAXIMUM SALARY OF ALL THE EMPLOYEES
   SELECT SAL
   FROM (SELECT ROWNUM SINO,SAL
        FROM (SELECT DISTINCT SAL 
              FROM EMP
              ORDER BY SAL DESC))
  WHERE SINO>(SELECT CEIL(COUNT(DISTINCT SAL)*50/100)
               FROM EMP);
    

-- Q9 WAQTD LAST 25% OF THE MINIMUM SALARY OF THE EMPLOYEES
     SELECT SAL
     FROM(SELECT ROWNUM SINO,SAL
          FROM (SELECT DISTINCT SAL 
                FROM EMP
                ORDER BY SAL ASC))
     WHERE SINO>(SELECT CEIL(COUNT(DISTINCT SAL)*75/100) FROM EMP);
         


-- Q10 WAQTD FIRST MAX SALARY AND THE LAST 3rd MAX OF THE SALARY
       SELECT SAL
       FROM(SELECT ROWNUM SINO,SAL
            FROM(SELECT DISTINCT SAL
                 FROM EMP
                 ORDER BY SAL DESC))
       WHERE SINO IN(1,3);
       ---??
       NOW SELECT SAL
FROM (
    SELECT ROWNUM RN, SAL
    FROM (
        SELECT DISTINCT SAL
        FROM EMP
        ORDER BY SAL DESC
    )
)
WHERE RN = 1
   OR RN = (SELECT COUNT(DISTINCT SAL) - 2 FROM EMP);
-- Q11 WAQTD FIRST 3 MIN SALARY AND THE LAST 25% OF THE MIN SALARY
       SELECT SAL 
       FROM(SELECT ROWNUM SINO,SAL
            FROM(SELECT DISTINCT SAL
                 FROM EMP
                 ORDER BY SAL)
       WHERE SINO<=3;


       --???

       SELECT SAL
FROM (
    SELECT ROWNUM RN, SAL
    FROM (
        SELECT DISTINCT SAL
        FROM EMP
        ORDER BY SAL ASC
    )
)
WHERE RN <= 3
   OR RN > (SELECT CEIL(COUNT(DISTINCT SAL) * 75 / 100) FROM EMP);
 
-- Q12 WAQTD 1ST, 3RD, 5TH MAX OF SALARY AND THE LAST SECOND MAX SALARY OF ALL THE EMPLOYEES.
      SELECT SAL 
      FROM(SELECT ROWNUM SINO ,SAL
           FROM(SELECT DISTINCT SAL
                FROM EMP
                ORDER BY SAL DESC))
     WHERE SINO = 2 or SINO IN(1,3,5);

     --???
     SELECT SAL
FROM (
    SELECT ROWNUM RN, SAL
    FROM (
        SELECT DISTINCT SAL
        FROM EMP
        ORDER BY SAL DESC
    )
)
WHERE RN IN (1, 3, 5)
   OR RN = (SELECT COUNT(DISTINCT SAL) - 1 FROM EMP);

-- Q13 WAQTD LAST 5TH MINIMUM SALARY OF THE EMPLOYEES.
       SELECT SAL
       FROM(SELECT ROWNUM SINO ,SAL
            FROM(SELECT DISTINCT SAL
                 FROM EMP
                 ORDER BY SAL))
       WHERE SINO = (
    SELECT COUNT(DISTINCT SAL) - 4
    FROM EMP
);