-- Q1 WAQTD names of the employees if char 'S' is present in the name
      
-- Q2 WAQTD names of the employees if char 'A' is present at least 2 times in the name

-- Q3 WAQTD names of the employees if char 'R' is present at least 3 times in the name

-- Q4 WAQTD names of the employees if string 'LL' is present at least once in the name

-- Q5 WAQTD names of the employees if char 'A' is present exactly 2 times in the name

-- Q6 WAQTD names of the employees if char 'A' is present exactly 4 times in the name

-- Q7 WAQTD details of the employees if string 'MAN' is present in their designations