-- REPLACE()
-- SYNTAX: REPLACE('Original_str', 'Substr' [, 'newstr'])


-- Q1 WAQTD NAMES OF ALL THE EMPLOYEES BY REPLACING 'A' WITH '$'
    SELECT ENAME,REPLACE(ENAME,'A','$')
    FROM EMP;

-- Q2 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'A' IS PRESENT EXACTLY 2 TIMES IN THE NAME
    SELECT ename
    from emp
    where length(ename)-length(replace(ename,'A',''))=2;

-- Q3 WAQTD NAMES AND NUMBER OF TIMES CHAR 'A' PRESENT IN EACH NAME
      select ename,length(ename)-length(replace(ename,'A','')) AS NO_A
      FROM EMP;

-- Q4 WAQTD NUMBER OF TIMES CHAR 'S' PRESENT IN 'QSPIDERS/JSPIDERS'
      SELECT LENGTH('JSPIDERS')-LENGTH(REPLACE(''JSPIDERS',','S','')) AS NO_S
      FROM DUAL;

-- Q5 WAQTD NUMBER OF TIMES CHAR 'S' PRESENT IN 
    SELECT LENGTH('SUCCESS')-LENGTH(REPLACE('SUCCESS','S','')) AS NO_S
    FROM DUAL;

-- Q6 WAQTD NUMBER OF TIMES CHAR 'E' PRESENT IN 'ENGINEERING'
     SELECT LENGTH('ENGINEERING')-LENGTH(REPLACE('ENGINEERING','E','')) AS NO_E
     FROM DUAL;
