-- SUBSTR()
-- SYNTAX: SUBSTR('Original_string', position [, length])


-- Q1 WAQTD NAMES OF THE EMPLOYEES IF THE NAME STARTS WITH 'A', 'S', 'T'
      select ename 
      from emp
      where substr(ename,1,1) in('A','S','T');


-- Q2 WAQTD EXTRACT FIRST 3 CHARACTERS OF EACH NAME
      SELECT SUBSTR(ENAME,1,3)
      FROM EMP;

-- Q3 WAQTD FIRST HALF OF EMPLOYEE NAMES
       SELECT ENAME,SUBSTR(ENAME,1,FLOOR(LENGTH(ENAME)/2))
       FROM EMP;

-- Q4 WAQTD TO EXTRACT SECOND HALF OF EMPLOYEE NAME
      
      SELECT ENAME, SUBSTR(ENAME, 1, CEIL(LENGTH(ENAME)/2))
      FROM EMP;
-- HINT:
-- SELECT ENAME, SUBSTR(ENAME, LENGTH(ENAME)/2 + 1)
-- FROM EMP;


-- Q5 LIST THE NAMES OF THE EMPLOYEES IF THEIR NAME'S 3RD CHARACTER IS 'A'
-- HINT:
SELECT ENAME
 FROM EMP
 WHERE SUBSTR(ENAME, 3, 1) = 'A';


-- Q6 WAQTD THE NAMES LEAVING THE FIRST AND THE LAST CHARACTER
      SELECT SUBSTR(ENAME,2,LENGTH(ENAME)-2)
      FROM EMP;

-- Q7 WAQTD NAMES OF THE EMPLOYEES BY REVERSING THE SECOND HALF OF THE NAME
-- EX: I/P SMITH --> O/P SMHTI
-- HINT:
 SELECT ENAME,
        SUBSTR(ENAME, 1, LENGTH(ENAME)/2) ||
        REVERSE(SUBSTR(ENAME, LENGTH(ENAME)/2 + 1))
 FROM EMP;


-- Q8 WAQTD NAMES OF THE EMPLOYEES BY REVERSING THE FIRST AND THE SECOND HALF
-- EX: I/P SMITH --> O/P MSHTI
       SELECT ENAME,
             REVERSE(SUBSTR(ENAME,1,LENGTH(ENAME)/2))||
             REVERSE(SUBSTR(ENAME,LENGTH(ENAME)/2+1))
             FROM EMP;
-- Q9 WAQTD DETAILS OF THE EMPLOYEES IF 'MAN' IS PRESENT AS FIRST 3 CHARACTERS IN THEIR DESIGNATIONS
        SELECT *
        FROM EMP
        WHERE SUBSTR(JOB,1,3)='MAN';
-- Q10 WAQTD DETAILS OF THE EMPLOYEES IF 'MAN' IS PRESENT AS LAST 3 CHARACTERS IN THEIR DESIGNATIONS
       SELECT *
       FROM EMP
       WHERE SUBSTR(JOB,-3)='MAN';