-- INSTR()
-- SYNTAX:
-- INSTR('Original_str', 'sub_str', position [, nth_occurrence])


-- Q1 WAQTD NAMES OF THE EMPLOYEES IF THE NAME CHAR 'A' PRESENT IN IT WITHOUT USING LIKE OPERATOR
      select ename
      from emp
      where instr(ename,'A',1,1)>0;

-- Q2 WAQTD DETAILS OF THE EMPLOYEE IF THE NAME HAS CHAR 'L' PRESENT AT LEAST 2 TIMES, WITHOUT USING LIKE OPERATOR
      SELECT *
      FROM EMP
      WHERE INSTR(ENAME,'L',2)>0;

-- Q3 WAQTD LIST OF EMPLOYEES WHO ARE WORKING IN A DESIGNATION THAT HAS A STRING 'MAN' IN IT
      SELECT *
      FROM EMP
      WHERE INSTR(JOB,'MAN',1,1)>0;

-- Q4 WAQTD NAMES OF THE EMPLOYEES IF THEIR NAME HAS CHAR 'S' PRESENT EXACTLY ONCE
      SELECT ENAME
      FROM EMP
      WHERE  ANDINSTR(ENAME,'S',1,1)>0 INSTR(ENAME,'S',1,2)=0;




-- Q5 WAQTD NAMES OF THE EMPLOYEES IF THEIR NAME HAS CHAR 'R' PRESENT EXACTLY TWICE
      SELECT ENAME
      FROM EMP
      WHERE INSTR(ENAME,'R',1,2)>0 AND INSTR(ENAME,'R',1,3)=0;



-- ============================
-- ASSIGNMENTS
-- ============================

-- Q1 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'S' IS PRESENT IN THE NAME
      SELECT ENAME 
      FROM EMP
      WHERE INSTR(ENAME,'S')>0;


-- Q2 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'A' IS PRESENT AT LEAST 2 TIMES
      SELECT ENAME
      FROM EMP
      WHERE INSTR(ENAME,'A',1,2)>0;

-- Q3 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'R' IS PRESENT AT LEAST 3 TIMES
     SELECT ENAME
     FROM EMP
     WHERE INSTR(ENAME,'R',1,3)>0;

-- Q4 WAQTD NAMES OF THE EMPLOYEES IF STRING 'LL' IS PRESENT AT LEAST ONCE
       SELECT ENAME
       FROM EMP
       WHERE INSTR(ENAME,'LL',1,1)>0;


-- Q5 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'A' IS PRESENT EXACTLY 2 TIMES
    SELECT ENAME
    FROM EMP
    WHERE INSTR(ENAME,'A',1,2)>0 AND INSTR(ENAME,'A',1,3)=0 
-- Q6 WAQTD NAMES OF THE EMPLOYEES IF CHAR 'A' IS PRESENT EXACTLY 4 TIMES
      SELECT ENAME
      FROM EMP
      WHERE INSTR(ENAME,'A',1,4)>0 AND INSTR(ENAME,'A',1,5)=0;

-- Q7 WAQTD DETAILS OF THE EMPLOYEES IF A STRING 'MAN' IS PRESENT  IN THEIR DESIGNATIONS
      SELECT *
      FROM EMP
      WHERE INSTR(JOB,'MAN',1,1)>0;